apiVersion: v1
kind: ConfigMap
metadata:
  name: gem-config-map
  namespace: {{ .Values.common.namespace }}
data:
  gem-url: "http://gem.web.authenticator.com"
  loki-url: "http://monitoring-loki.monitoring.svc.cluster.local:3100/loki/api/v1/push"