apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: gem-ingress
  namespace: {{ .Values.common.namespace }}
spec:
  ingressClassName: nginx
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: {{ printf "%s-service" .Values.apiGateway.name }}
            port:
              number: {{ .Values.common.port }}
