{
 "title": "finanse-adapter",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "service", "query": "finanse-adapter" },
   {
    "name": "client",
    "query": {
     "query": "label_values(metered_client_seconds{app=~\"$service\"},client)"
    }
   },
   {
    "name": "collection",
    "query": {
     "query": "label_values(metered_repository_seconds{app=~\"$service\"},repository)"
    }
   },
   {
    "name": "endpoint",
    "query": {
     "query": "label_values(http_server_requests_seconds_count{app=~\"$service\", uri!~\"$excluded_path\"},uri)"
    }
   },
   {
    "name": "excluded_path",
    "query": "/actuator/health,/actuator/prometheus, /v3/api-docs/swagger-config,/v3/api-docs,/swagger-ui.html, /swagger-ui*/*swagger-initializer.js, /swagger-ui*/**, /**\n"
   }
  ]
 },
 "panels": [
  { "title": "General", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Requests for last selected range by method",
   "type": "piechart",
   "gridPos": { "h": 15, "w": 16, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(method, uri) (increase(http_server_requests_seconds_count{app=~\"$service\", uri!~\"$excluded_path\"}[$__range]))",
     "legendFormat": "{{method}} {{uri}}"
    }
   ]
  },
  {
   "title": "JVM versions",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(version, runtime) (jvm_info{app=~\"$service\"})",
     "legendFormat": "{{version}}/{{runtime}}"
    }
   ]
  },
  {
   "title": "Application ready time (seconds)",
   "type": "stat",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(application_ready_time_seconds{app=~\"$service\"})"
    }
   ]
  },
  {
   "title": "Requests per status family",
   "type": "piechart",
   "gridPos": { "h": 15, "w": 16, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(status) (increase(http_server_requests_seconds_count{app=~\"$service\", uri!~\"$excluded_path\"}[$__range]))",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "Kubernetes instances",
   "type": "stat",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_deployment_status_replicas_available{deployment=~\".*$service.*\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "SLA",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_seconds_count{app=~\"$service\", uri!~\"$excluded_path\", status=~\"2..\"}[$__range])) / sum(rate(http_server_requests_seconds_count{app=~\"$service\", uri!~\"$excluded_path\",status=~\"2..|5..\"}[$__range]))",
     "legendFormat": "2xx/xxx (4xx excluded)"
    }
   ]
  },
  {
   "title": "Cumulated incoming traffic on all endpoints: per status code",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by (status) (increase(http_server_requests_seconds_count{app=~\"$service\", uri!~\"$excluded_path\"}[$__rate_interval]))",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "Cumulated incoming traffic: per method",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by (uri,method) (increase(http_server_requests_seconds_count{app=\"$service\", uri!~\"$excluded_path\"}[$__rate_interval]))",
     "legendFormat": "{{method}} {{uri}}"
    }
   ]
  },
  {
   "title": "endpoints response times: from all hosts",
   "type": "state-timeline",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 44 },
   "targets": [
    {
     "expr": "min(max_over_time(http_server_requests_seconds{app=~\"$service\", uri!~\"$excluded_path\"}[$__interval])) > 0",
     "legendFormat": "min"
    },
    {
     "expr": "avg by(quantile) (max_over_time(http_server_requests_seconds{app=~\"$service\", uri!~\"$excluded_path\"}[$__interval])) > 0",
     "legendFormat": "{{quantile}}"
    },
    {
     "expr": "max(max_over_time(http_server_requests_seconds{app=~\"$service\", uri!~\"$excluded_path\"}[$__interval])) > 0",
     "legendFormat": "max"
    }
   ]
  },
  {
   "title": "Cumulated outgoing traffic: per method",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by(handler, client) (increase(metered_client_count_total{app=~\"$service\"}[$__rate_interval]))",
     "legendFormat": "{{client}} {{handler}}"
    }
   ]
  },
  {
   "title": "External services response times",
   "type": "state-timeline",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 52 },
   "targets": [
    {
     "expr": "min(max_over_time(metered_client_seconds{app=~\"$service\"}[$__interval])) > 0",
     "legendFormat": "min"
    },
    {
     "expr": "avg by(quantile) (max_over_time(metered_client_seconds{app=~\"$service\"}[$__interval])) > 0",
     "legendFormat": "{{quantile}}"
    },
    {
     "expr": "max(max_over_time(metered_client_seconds{app=~\"$service\"}[$__interval])) > 0",
     "legendFormat": "max"
    }
   ]
  },
  {
   "title": "Repository traffic: per method",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 61 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by(handler, repository) (increase(metered_repository_counter_total{app=~\"$service\"}[$__rate_interval]))",
     "legendFormat": "{{repository}} {{handler}}"
    }
   ]
  },
  {
   "title": "Repository times",
   "type": "state-timeline",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 61 },
   "targets": [
    {
     "expr": "min(max_over_time(metered_repository_seconds{app=~\"$service\"}[$__interval])) > 0",
     "legendFormat": "min"
    },
    {
     "expr": "avg by(quantile) (max_over_time(metered_repository_seconds{app=~\"$service\"}[$__interval])) > 0",
     "legendFormat": "{{quantile}}"
    },
    {
     "expr": "max(max_over_time(metered_repository_seconds{app=~\"$service\"}[$__interval])) > 0",
     "legendFormat": "max"
    }
   ]
  },
  {
   "title": "Kubernetes",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 70 },
   "collapsed": true,
   "panels": [
    {
     "title": "Kubernetes container restart",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 71 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum(kube_pod_container_status_restarts_total{container=~\"$service\"})",
       "target": "alias(summarize(derivative(stats.tech.marathon.app-state.*.api.okapi.webapi-showitem.task_failures.count), '10minutes'), 'Failures')"
      }
     ]
    },
    {
     "title": "Kubernetes instances",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 71 },
     "targets": [
      {
       "expr": "kube_deployment_status_replicas_available{deployment=~\".*$service.*\"}",
       "legendFormat": "{{ cluster }} replicas_available"
      }
     ]
    },
    {
     "title": "K8s - MEM",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 79 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum by(pod) (container_memory_usage_bytes{pod=~\".*$service.*\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "K8s CPU seconds",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 79 },
     "targets": [
      {
       "expr": "sum by(pod) (increase(container_cpu_system_seconds_total{pod=~\".*$service.*\"}[$__rate_interval]))",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Mongo",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 71 },
   "collapsed": true,
   "panels": [
    {
     "title": "Mongo requests count",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 72 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum by(collection, command) (increase(mongodb_driver_commands_seconds_count{app=~\"$service\",collection!~\"unknown\"}[$__rate_interval]))",
       "legendFormat": "{{collection}} {{command}}"
      }
     ]
    },
    {
     "title": "MongoDB commands time",
     "type": "state-timeline",
     "gridPos": { "h": 9, "w": 19, "x": 0, "y": 82 },
     "targets": [
      {
       "expr": "min(mongodb_driver_commands_seconds_max{app=~\"$service\",collection!~\"unknown\"})",
       "legendFormat": "min"
      },
      {
       "expr": "avg(mongodb_driver_commands_seconds_max{app=~\"$service\",collection!~\"unknown\"})",
       "legendFormat": "avg"
      },
      {
       "expr": "max(mongodb_driver_commands_seconds_max{app=~\"$service\",collection!~\"unknown\"})",
       "legendFormat": "max"
      }
     ]
    },
    {
     "title": "Mongo rq/s",
     "type": "stat",
     "gridPos": { "h": 9, "w": 5, "x": 19, "y": 82 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(irate(mongodb_driver_commands_seconds_count{app=~\"$service\",collection!~\"unknown\"}[$__interval]))"
      }
     ]
    }
   ]
  },
  {
   "title": "System",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 72 },
   "collapsed": true,
   "panels": [
    {
     "title": "Memory used",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 17, "x": 0, "y": 73 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum(jvm_memory_used_bytes{app=~\"$service\"})",
       "legendFormat": "{{shortname}}"
      }
     ]
    },
    {
     "title": "Memory usage %",
     "type": "gauge",
     "gridPos": { "h": 10, "w": 7, "x": 17, "y": 73 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(jvm_memory_used_bytes{app=~\"$service\"}) / sum(jvm_memory_max_bytes{app=~\"$service\"})"
      }
     ]
    },
    {
     "title": "CPU usage",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 17, "x": 0, "y": 83 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "sum(system_cpu_usage{app=~\"$service\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "CPU usage %",
     "type": "gauge",
     "gridPos": { "h": 10, "w": 7, "x": 17, "y": 83 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(system_cpu_usage{app=~\"$service\"})"
      }
     ]
    }
   ]
  },
  {
   "title": "JVM",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 73 },
   "collapsed": true,
   "panels": [
    {
     "title": "JVM heap usage",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 94 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "sum by (area) (jvm_memory_used_bytes{app=~\"$service\"})",
       "legendFormat": "{{area}}"
      }
     ]
    },
    {
     "title": "GC collections",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 102 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "sum(jvm_gc_max_data_size_bytes{app=~\"$service\"})",
       "legendFormat": "free"
      },
      {
       "expr": "sum(jvm_gc_live_data_size_bytes{app=~\"$service\"})",
       "legendFormat": "In Use"
      }
     ]
    }
   ]
  },
  {
   "title": "Threads",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 74 },
   "collapsed": true,
   "panels": [
    {
     "title": "Thread Pools Count",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 75 },
     "targets": [
      {
       "expr": "sum(jvm_threads_live_threads{app=~\"$service\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Total number of application threads",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 75 },
     "targets": [
      {
       "expr": "sum(jvm_threads_started_threads_total{app=~\"$service\"})",
       "legendFormat": "{{dc}} - {{threadPoolName}}"
      }
     ]
    },
    {
     "title": "Thread Pools Task Queue Capacity",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 83 },
     "targets": [
      {
       "expr": "sum by (state) (jvm_threads_states_threads{app=~\"$service\"})",
       "legendFormat": "{{state}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Endpoint: $endpoint",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 75 },
   "repeat": "endpoint",
   "collapsed": true,
   "panels": [
    {
     "title": "Cumulated incoming traffic on $endpoint: per status code",
     "type": "timeseries",
     "gridPos": { "h": 13, "w": 24, "x": 0, "y": 76 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum by (status) (increase(http_server_requests_seconds_count{app=~\"$service\", uri=~\"$endpoint\"}[$__rate_interval]))",
       "legendFormat": "{{statusCode}}"
      }
     ]
    },
    {
     "title": "Cumulated incoming traffic on $endpoint: per method",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 89 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum by (uri,method) (increase(http_server_requests_seconds_count{app=~\"$service\", uri=~\"$endpoint\"}[$__rate_interval]))",
       "legendFormat": "{{method}}"
      }
     ]
    },
    {
     "title": "endpoint $endpoint response times",
     "type": "state-timeline",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 89 },
     "targets": [
      {
       "expr": "min(max_over_time(http_server_requests_seconds{app=~\"$service\", uri=~\"$endpoint\"}[$__interval])) > 0",
       "legendFormat": "min"
      },
      {
       "expr": "avg by(quantile) (max_over_time(http_server_requests_seconds{app=~\"$service\", uri=~\"$endpoint\"}[$__interval])) > 0",
       "legendFormat": "{{quantile}}"
      },
      {
       "expr": "max(max_over_time(http_server_requests_seconds{app=~\"$service\", uri=~\"$endpoint\"}[$__interval])) > 0",
       "legendFormat": "max"
      }
     ]
    }
   ]
  },
  {
   "title": "Client: $client",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 78 },
   "repeat": "client",
   "collapsed": true,
   "panels": [
    {
     "title": "External Client $client Rate",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 79 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum by(handler, client) (increase(metered_client_count_total{app=~\"$service\",client=~\"$client\"}[$__rate_interval]))",
       "legendFormat": "{{method}}"
      }
     ]
    },
    {
     "title": "Client $client Times",
     "type": "state-timeline",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 79 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "min (max_over_time(metered_client_seconds{app=~\"$service\",client=\"$client\"}[$__interval])) > 0",
       "legendFormat": "min"
      },
      {
       "expr": "avg by(quantile) (max_over_time(metered_client_seconds{app=~\"$service\",client=\"$client\"}[$__interval])) > 0",
       "legendFormat": "{{quantile}}"
      },
      {
       "expr": "max (max_over_time(metered_client_seconds{app=~\"$service\",client=\"$client\"}[$__interval])) > 0",
       "legendFormat": "max"
      }
     ]
    }
   ]
  },
  {
   "title": "Mongo collection : $collection",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 79 },
   "repeat": "collection",
   "collapsed": true,
   "panels": [
    {
     "title": "Mongo Collection $collection Rate",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 12, "x": 0, "y": 89 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum by(handler, repository) (increase(metered_repository_counter_total{app=~\"$service\", repository=~\"$collection\"}[$__rate_interval]))",
       "legendFormat": "{{method}}"
      }
     ]
    },
    {
     "title": "Mongo Collection $collection Time",
     "type": "state-timeline",
     "gridPos": { "h": 11, "w": 12, "x": 12, "y": 89 },
     "targets": [
      {
       "expr": "min(max_over_time(metered_repository_seconds{app=~\"$service\", repository=~\"$collection\"}[$__interval])) > 0",
       "legendFormat": "min"
      },
      {
       "expr": "avg by(quantile) (max_over_time(metered_repository_seconds{app=~\"$service\", repository=~\"$collection\"}[$__interval])) > 0",
       "legendFormat": "{{quantile}}"
      },
      {
       "expr": "max(max_over_time(metered_repository_seconds{app=~\"$service\", repository=~\"$collection\"}[$__interval])) > 0",
       "legendFormat": "max"
      }
     ]
    }
   ]
  }
 ]
}