apiVersion: v1
kind: Secret
metadata:
  name: loki-datasources
  labels:
    grafana_datasource: 'true'
stringData:
  loki.yaml: |-
    apiVersion: 1
    datasources:
      - name: Loki
        type: loki
        uid: loki
        access: proxy
        url: http://monitoring-loki:3100
        jsonData:
          maxLines: 1000
          alertmanagerUid: alertmanager