apiVersion: v1
kind: Secret
metadata:
  name: prometheus-datasource
  labels:
    grafana_datasource: 'true'
stringData:
  prometheus.yaml: |-
    apiVersion: 1
    datasources:
      - name: Prometheus
        type: prometheus
        uid: prometheus
        access: proxy
        url: http://monitoring-prometheus-server:80
        jsonData:
          timeInterval: 30s